### GET request to example server
GET http://localhost:8080



###
GET http://localhost:8080/user-profile

###

POST http://localhost:8080/user-profile
Content-Type: application/json

{
    "name" : "Priscilla",
    "dateOfBirth": "1994-05-27",
    "weightKg" : 75,
    "heightCm" : 170,
    "sex": "FEMALE",
    "activityLevel" : "MODERATE",
    "intensity": "RECOMMENDED",
    "goal": "LOSE_FAT"

}

###
GET http://localhost:8080/user-profile/26

###

GET http://localhost:8080/api/foods/search?query=cheese

###

GET https://api.nal.usda.gov/fdc/v1/foods/search?query=cheese&api_key=GbfayhAVb24HIvQEFfkdxpVOEWlp260xEPF3wyMy


###
GET localhost:8080/api/foods/search?query=milk

###
GET localhost:8080/api/foods/search/cheese
###
GET localhost:8080/api/foods/search/2062204





