### GET request to example server
GET http://localhost:8080



###
GET http://localhost:8080/user-profile

###

POST http://localhost:8080/user-profile
Content-Type: application/json

{
    "name" : "Priscilla",
    "dateOfBirth": "1994-05-27",
    "weightKg" : 75,
    "heightCm" : 170,
    "sex": "FEMALE",
    "activityLevel" : "MODERATE",
    "intensity": "RECOMMENDED",
    "goal": "LOSE_FAT"

}

###
GET http://localhost:8080/user-profile/26

###

GET http://localhost:8080/api/foods/search?query=cheese

###

GET https://api.nal.usda.gov/fdc/v1/foods/search?query=cheese&api_key=GbfayhAVb24HIvQEFfkdxpVOEWlp260xEPF3wyMy


### get food list by query/externalapi
GET localhost:8080/api/foods/search?query=almond milk no sugar

### get food by id/externalapi
GET localhost:8080/api/foods/search/1909137

###
POST http://127.0.0.1:8080/user-profile/22/daily-logs/2026-02-02
Content-Type: application/json

{
    "fdcId": 2241814,
    "servingSize": 105
}

### get daily log for user
GET localhost:8080/user-profile/22/daily-logs/2026-02-04

### delete food log for user // update response code to 204
DELETE localhost:8080/user-profile/22/daily-logs/3/foods/5


### get specific log
GET localhost:8080/user-profile/22/daily-logs/3/foods/4

### get deployed
GET http://98.92.83.117:8080/user-profile



