### GET request to example server
GET http://localhost:8080



###
GET http://localhost:8080/user-profile

###

POST http://localhost:8080/user-profile
Content-Type: application/json

{
    "name" : "Ana",
    "dateOfBirth": "2003-02-11",
    "weightGrams" : 15,
    "heightCm" : "123",
    "activityLevel" : "ACTIVE",
    "goal": "MAINTAIN"
}

###
GET http://localhost:8080/user-profile/1/

