ALTER TABLE user_profile
    ADD COLUMN goal VARCHAR(255);

ALTER TABLE user_profile
    ALTER COLUMN goal SET NOT NULL;


CREATE TABLE IF NOT EXISTS macro_goal
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_profile_id  BIGINT                                 NOT NULL,
    calorie_target   INTEGER                                NOT NULL,
    protein_g        DOUBLE PRECISION                       NOT NULL,
    carbs_g          DOUBLE PRECISION                       NOT NULL,
    fat_g            DOUBLE PRECISION                       NOT NULL,
    is_active        BOOLEAN                                NOT NULL DEFAULT false,
    created_at       TIMESTAMP WITH TIME ZONE               NOT NULL DEFAULT now(),
    CONSTRAINT pk_macro_goal PRIMARY KEY (id),
    CONSTRAINT fk_macro_goal_user_profile
        FOREIGN KEY (user_profile_id)
            REFERENCES user_profile (id)
);
DROP TRIGGER IF EXISTS trg_macro_goal_updated_at ON macro_goal;

